### PR TITLE
WIP: Add linear trajectory and traj pt messages.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@fmauch: I'm not sure how much progress you've made with your FTP, but this is something I had lying around from an old project.

**Comment by fmauch** [comment]
Thanks, I'll include that into the design document we are currently working on

**Comment by gavanderhoorn** [comment]
I remember some discussion about whether to include tolerances and other meta-data at the `LinearTrajectory` level (such as flags to request early failure if IK solutions -- without configuration changes -- could not be found, or whether to explicitly allow such discontinuities).

For the tolerances I personally would probably put that in an action request wrapping this sort of message, as the message itself should accurately encode a Cartesian trajectory.

As for the flags: not sure why those were not included.

**Comment by gavanderhoorn** [comment]
As for IO (or other operations which should be synced with motion): I believe the idea was to use `time_from_start` and separate "IO trajectories". So instead of creating a union message type which supports everything (ie: motion, IO, other stuff), use composition and time-stamp based matching (ie: `LinearTrajectoryWithIO` or something similar).

Not sure how well that would scale though.

**Comment by gavanderhoorn** [comment]
Closing as this was just to document some earlier work.

**Pull request closed without merging**
